100 add a viewmodel for favorite sequences and add favorites to emojirepository
ITP2-G15/OpenEmojiPlatform pull request #113
Opened 2024-04-04 12:05 UTC by michaelbrusegard

IT IS DONE. closes #100. Created new repository instead of adding to EmojiReposiory because of seperation of concerns

2024-04-04 18:32 UTC, Andreasli02 requested changes
gj :)

2024-04-04 18:32 UTC, Andreasli02 commented on app/src/test/kotlin/com/platform/openemoji/favorites/FavoritesRepositoryTest.kt
> +            assertTrue(!actualFavorites.contains(favorite))
assertFalse and remove !

2024-04-04 18:32 UTC, Andreasli02 commented on app/src/main/kotlin/com/platform/openemoji/favorites/FavoritesRepository.kt
> +    }
IDE gives warning: If-Then foldable to '?:' 

You choose if you want to use elvis operator instead

2024-04-04 18:32 UTC, Andreasli02 commented on app/src/main/kotlin/com/platform/openemoji/favorites/FavoritesViewModel.kt
> +    val currentFavorite = _currentFavorite.asStateFlow()
Thought that this was supposed to be sequence? I personally think its a better name but you can choose.

2024-04-04 18:32 UTC, Andreasli02 commented on app/src/main/kotlin/com/platform/openemoji/favorites/FavoritesViewModel.kt
> +    }
This name is a little confusing for me.

2024-04-04 19:15 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/favorites/FavoritesViewModel.kt
> +    }
currentFavorite has an emojiSequence which is a string. The string given to the method (the emojiCode) is appended to the emojiSequence string aka appendToCurrentFavoriteEmojiSequence. It is a little long but it explains what it is

2024-04-07 22:20 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/favorites/FavoritesViewModel.kt
> +    val currentFavorite = _currentFavorite.asStateFlow()
currentFavorite is a favorite object that contains an emojiSequence

2024-04-07 22:27 UTC, michaelbrusegard commented
@Andreasli02 everything should be okay now

2024-04-08 09:17 UTC, merged