95 add favorites screen
ITP2-G15/OpenEmojiPlatform pull request #116
Opened 2024-04-04 20:43 UTC by YounesBB

The app should now have favorites screen that displays created emoji sequences. It looks like this: 
<img src="https://github.com/ITP2-G15/OpenEmojiPlatform/assets/125987914/5a03dfde-dd5b-4bfb-9a5a-d2027fbc5e2d" width="250" height="500">
Pop-up when pressing the delete button: 
<img src="https://github.com/ITP2-G15/OpenEmojiPlatform/assets/125987914/118bb1c8-b90f-4da5-bdc5-fe2329650cf9" width="250" height="500">
I believe having a delete button like this is more intuitive for a user. It is quite clear what the needed action is to delete a sequence. If we rather had the function so that the user needs to long press on a sequence in order to delete it, problems could arise. Not all users would know such a thing was possible. 

NOTE: The functionality for actually deleting a sequence after confirming yes is yet to be implemented. Also, the test for that would also need to be made.

2024-04-07 22:33 UTC, michaelbrusegard requested changes

2024-04-07 22:33 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/favorites/Sequence.kt
> +                fontSize = 20.sp,
use a predefined size for the text from materialTheme instead of defining your own size and weight

2024-04-07 22:33 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/favorites/Sequence.kt
> +                 * This is done to prevent the emojis from overflowing the screen
hmm will this work, emojis can be written as a combination of emojis but still only display as a single emoji. I think a better approach is to have the text overflow to the next line when it is too long

2024-04-07 22:33 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/favorites/Sequence.kt
> +                        fontSize = 22.sp,
use materialtheme for text

2024-04-07 22:33 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/favorites/Sequence.kt
> +                        Icon(Icons.Filled.ContentCopy, contentDescription = "Copy Icon")
content description should come from strings.xml

2024-04-07 22:33 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/favorites/Sequence.kt
> +                            contentDescription = "Delete Icon",
strings.xml^^

2024-04-07 22:33 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/favorites/Sequence.kt
> +                    Text("Yes")
strings.xml

2024-04-07 22:33 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/favorites/Sequence.kt
> +                    Text("No")
strings.xml

2024-04-08 10:30 UTC, YounesBB commented
@michaelbrusegard I implemented your suggested changes. Please have a look.

2024-04-08 12:17 UTC, michaelbrusegard approved these changes

2024-04-08 12:18 UTC, michaelbrusegard commented
LGTM, if we want to do UI changes we can do that later after user testing!

2024-04-08 12:18 UTC, merged