110 banner ad and link to emoji detail screen
ITP2-G15/OpenEmojiPlatform pull request #132
Opened 2024-04-18 09:03 UTC by taleeikenes

2024-04-18 11:21 UTC, OleAndreasER requested changes
Good. It works. Just a few small things.

Don't you think the banner ad should be on all screens? You could put it in Scaffold topBar.

2024-04-18 11:21 UTC, OleAndreasER commented on app/src/main/res/values/strings.xml
> +>>>>>>> dev
">>>>>>> dev" is from the merge. It shouldn't be here.

2024-04-18 11:21 UTC, OleAndreasER commented on app/src/main/kotlin/com/platform/openemoji/screens/EmojiDetailScreen.kt
> +            }
Description needs material theme color. It's currently the same color as background on my phone.

2024-04-18 11:21 UTC, OleAndreasER commented on app/src/main/kotlin/com/platform/openemoji/screens/EmojiDetailScreen.kt
> +    val annotatedString =
"annotatedString" -> "styledEmojiDescription" or add a comment so it's easier for the reader to figure out what this is.

2024-04-19 07:50 UTC, taleeikenes commented on app/src/main/kotlin/com/platform/openemoji/screens/EmojiDetailScreen.kt
> +            }
If I add color - it disappears for me, but I added this:
`withStyle(
                style =
                    MaterialTheme.typography.titleMedium.toSpanStyle().copy(
                        color = MaterialTheme.colorScheme.onSurface,
                    ),
            )`
Does it work for you then?

2024-04-22 09:03 UTC, merged