101 create guessing game screen composable
ITP2-G15/OpenEmojiPlatform pull request #140
Opened 2024-04-23 14:10 UTC by Andreasli02

Added Gamescreen UI mostly done by @aurorakennedy. UI has color and sound feedback.

2024-04-25 11:19 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/navigation/Screen.kt
why does the Gamescreen have the whole package name in screen.kt. while the other screens don't have it?

2024-04-25 11:27 UTC, michaelbrusegard requested changes

2024-04-25 11:27 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/screens/GameScreen.kt
> +                    text = "Level $levelCounter \n",
this text is hard coded. Use text from strings.xml and you can have the levelcounter as a variable in the strings.xml

2024-04-25 11:27 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/screens/GameScreen.kt
> +                                    fontSize = 25.sp,
use materialtheme for text style

2024-04-25 11:27 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/screens/GameScreen.kt
> +                                containerColor =
you also need to set the content color to be onError, onPrimary etc

2024-04-25 11:27 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/screens/GameScreen.kt
> +                currentLevel?.alternatives?.forEachIndexed { index, alternative ->
You need to handle when there isnt a level for the levelcounter, when it is null. For example show some text that says you have completed all levels or something.

2024-04-25 11:27 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/screens/GameScreen.kt
> +                    style = TextStyle(fontSize = 40.sp),
use materialtheme for textstyle

2024-04-25 11:27 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/screens/GameScreen.kt
> +                        text = it.emojiQuestion,
use materiltheme for textstyle

2024-04-25 11:27 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/screens/GameScreen.kt
> +                    .height(300.dp)
why do we have to hardcode a specific height for the card? Isnt it better to use padding?

2024-04-25 11:27 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/screens/GameScreen.kt
> +                                .fillMaxWidth(1f),
1f?

2024-04-25 11:27 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/screens/GameScreen.kt
> +                    text = "Level $levelCounter \n",
also write levelCounter + 1 so it starts at level 1 since lists are 0 indexed

2024-04-25 15:03 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/screens/GameScreen.kt
> +                    .height(300.dp)
This has not been resolved. I think the emojiQuestion should b forced to not expand from a single line, and then we use padding instead of hardcoding a specific height

2024-04-25 15:03 UTC, michaelbrusegard requested changes

2024-04-25 15:03 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/navigation/Screen.kt
> +    object GameScreen : Screen("com.platform.openemoji.screens.GameScreen")
Why do we write the whole package name here instead of not just GameScreen?

2024-04-25 15:04 UTC, michaelbrusegard commented
@Andreasli02 A few more things to fix. Also I want the text to be centered when there are no levels left :). You can work on whenever you have time so dont stress about it

2024-04-26 11:16 UTC, Andreasli02 commented on app/src/main/kotlin/com/platform/openemoji/screens/GameScreen.kt
> +                    .height(300.dp)
No the card should have a specific height. You will see that all of our other cards is also done this way. Code is refactored so it should be alot more readable now and I have also added tests.

2024-04-27 12:03 UTC, michaelbrusegard requested changes

2024-04-27 12:03 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/game/GameQuestionCard.kt
> +                .height(250.dp)
Don't have a hardcoded height. Make the text so it doesnt expand over a single line and set padding instead

2024-04-27 12:03 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/screens/GameScreen.kt
> +                    .height(300.dp)
ok

2024-04-27 12:03 UTC, michaelbrusegard commented on app/src/main/kotlin/com/platform/openemoji/game/GameQuestionCard.kt
> +                .height(250.dp)
nvm

2024-04-27 12:07 UTC, michaelbrusegard approved these changes
LGTM, hope I did not miss anything. MERGE

2024-04-27 12:07 UTC, merged