add unit test for EmojiCatalogue
ITP2-G15/OpenEmojiPlatform pull request #52
Opened 2024-02-29 09:39 UTC by michaelbrusegard

added unit test to the catalogue methods

2024-02-29 10:05 UTC, Steffenriv commented on app/src/test/kotlin/com/platform/openemoji/emoji/catalogue/EmojiCatalogueTest.kt
> +        Emoji(
initialise name and type, but do not set value here. That should be done in setup! Not really that important, but just to have a standard.

2024-02-29 10:09 UTC, Steffenriv requested changes
set value of emoji variables inside setup function

2024-02-29 11:03 UTC, OleAndreasER commented on app/src/test/kotlin/com/platform/openemoji/emoji/catalogue/EmojiCatalogueTest.kt
> +        val expected =
"testByCategory" ?

2024-02-29 12:02 UTC, michaelbrusegard commented on app/src/test/kotlin/com/platform/openemoji/emoji/catalogue/EmojiCatalogueTest.kt
> +        Emoji(
@OleAndreasER wanted them to be defined here instead of in setup. He also wanted me to move EmojiCatalogue up there instead of having lateinit. I am not sure, we should probably agree upon a standard for this. Is there a specific reason to have it in setup?

2024-02-29 12:04 UTC, michaelbrusegard commented
> set value of emoji variables inside setup function

we need to agree upon a standard

2024-03-05 08:40 UTC, Steffenriv approved these changes

2024-03-05 08:41 UTC, merged