36 create navigation system
ITP2-G15/OpenEmojiPlatform pull request #62
Opened 2024-03-07 14:05 UTC by Steffenriv

Created a new navigation system that centralizes all navigation in one folder system. Removes need for navhosts in other parts of the system. Updated files to make this system work for the whole architecture.
Closes #36

2024-03-07 15:29 UTC, Steffenriv commented
Ignore duplicate commits, happened because i double rebased with local branch instead of origin and dev. My bad 👎

2024-03-07 16:45 UTC, OleAndreasER requested changes
Well done :)
- Returning from an emoji page should not reset the search page.  
- Bottom nav bar has different animation when pressing the text vs the icon.  
- Tests fail.  
- "NavigationItem" is not so descriptive. Isn't it a "Screen"? Or a "Route" (then also: Route.route -> Route.name)?

2024-03-07 16:45 UTC, OleAndreasER commented on app/src/main/kotlin/com/platform/openemoji/navigation/Navigation.kt
> +                    val emoji = emojiTitle?.let { it1 -> emojiCatalogue.emoji(it1) }
If you're going to name the parameter, give it a real name. "title"? The "it" from outside should also be named to "paddingValues".

2024-03-07 16:45 UTC, OleAndreasER commented on app/src/main/kotlin/com/platform/openemoji/screens/SearchScreen.kt
> +                maxEmojisPerGrid = 15,
15 emojis max is only supposed to be in "Overview".

2024-03-07 16:45 UTC, OleAndreasER commented on app/src/main/kotlin/com/platform/openemoji/screens/SearchScreen.kt
> +                listOf(stringResource(R.string.overview)) + emojiCatalogue.categories,
stringResource(R.string.overview) -> overview

2024-03-07 16:45 UTC, OleAndreasER commented on app/src/main/kotlin/com/platform/openemoji/screens/SearchScreen.kt
>              // Remember the string resource here
This comment (not by you) is misleading and unnecessary. There is no remembering going on here.

2024-03-07 16:45 UTC, OleAndreasER commented on app/src/main/kotlin/com/platform/openemoji/screens/SearchScreen.kt
> +                maxEmojisPerGrid = 15,
If you switch to remembering, not the categorizedEmojis, but just the category name, you can use that to determine max emojis.

2024-03-07 16:45 UTC, OleAndreasER commented on app/src/main/kotlin/com/platform/openemoji/screens/SearchScreen.kt
>          SearchField(query)
This is not yours, but I think SearchField shouldn't have access to the mutable state "query", but instead should be provided a setter function: "SearchField { newQuery -> query.value = newQuery }".   

https://developer.android.com/jetpack/compose/architecture#udf

2024-03-07 18:09 UTC, Steffenriv commented on app/src/main/kotlin/com/platform/openemoji/screens/SearchScreen.kt
>              // Remember the string resource here
Removed it, does not need to be here, probably was added during rebase and i missed it when going over and did some minor tweaks.

2024-03-07 18:09 UTC, Steffenriv commented on app/src/main/kotlin/com/platform/openemoji/screens/SearchScreen.kt
> +                listOf(stringResource(R.string.overview)) + emojiCatalogue.categories,
Fixed!

2024-03-07 18:09 UTC, Steffenriv commented on app/src/main/kotlin/com/platform/openemoji/screens/SearchScreen.kt
> +                maxEmojisPerGrid = 15,
Fixed, a bit wonky probably, but works well so.

2024-03-07 18:09 UTC, Steffenriv commented on app/src/main/kotlin/com/platform/openemoji/navigation/Navigation.kt
> +                    val emoji = emojiTitle?.let { it1 -> emojiCatalogue.emoji(it1) }
Fixed!

2024-03-07 18:20 UTC, Steffenriv commented on app/src/main/kotlin/com/platform/openemoji/screens/SearchScreen.kt
>          SearchField(query)
fixed some minor issues now, will look at this a bit later alongside these points:
-Returning from an emoji page should not reset the search page.
-Bottom nav bar has different animation when pressing the text vs the icon.
Tests fail.
-"NavigationItem" is not so descriptive. Isn't it a "Screen"? Or a "Route" (then also: Route.route -> Route.name)? 
In regards to those points i have some questions:
-Quite interesting have not really thought about it. It does return to previous route (i.e. goes back to search page) used, so not really certain what i can do about it.
- No wonder lol, have put navigation it in the completly wrong place. (fixed)
-NavigationItem is actually quite common to use, but i agree it is not that good, can change to screen as i think that would suit best)

2024-03-07 18:23 UTC, Steffenriv commented on app/src/main/kotlin/com/platform/openemoji/screens/SearchScreen.kt
>          SearchField(query)
In regards to test fail, which tests are you referring to?

2024-03-07 19:21 UTC, OleAndreasER commented on app/src/main/kotlin/com/platform/openemoji/screens/SearchScreen.kt
>          SearchField(query)
EmojiCatalogueUiTest fails for me.

2024-03-07 19:30 UTC, Steffenriv commented on app/src/main/kotlin/com/platform/openemoji/screens/SearchScreen.kt
>          SearchField(query)
Will look into that 👍

2024-03-07 23:43 UTC, Steffenriv commented on app/src/main/kotlin/com/platform/openemoji/screens/SearchScreen.kt
>          SearchField(query)
@OleAndreasER  I have now fixed the test issue, as well Bottom bar different animation, swapped to screen from navigationItem. The only part where i am uncertain if i am able to actually fix properly is the refresh on return, i don't really know where to start.

2024-03-08 08:26 UTC, OleAndreasER commented on app/src/main/kotlin/com/platform/openemoji/screens/SearchScreen.kt
> +                maxEmojisPerGrid = 15,
Here's what I imagined:  
```
    val overview = stringResource(R.string.overview)
    val category = remember { mutableStateOf(overview) }

```
```
            CategoryScrollCarousel(
                listOf(overview) + emojiCatalogue.categories,
            ) { newCategory ->
                category.value = newCategory
            }
```
```
            EmojiCatalogueUi(
                emojis =
                    if (category.value == overview) {
                        emojiCatalogue.byCategory
                    } else {
                        emojiCatalogue.bySubCategory(category.value) ?: emptyMap()
                    },
                maxEmojisPerGrid =
                    if (category.value == overview) {
                        15
                    } else {
                        null
                    },
                navController = navController,
            )

```

2024-03-08 08:30 UTC, OleAndreasER commented on app/src/main/kotlin/com/platform/openemoji/screens/SearchScreen.kt
>          SearchField(query)
Very good! Returning can be fixed in another issue. It shouldn't be slowing this issue down.

2024-03-08 08:35 UTC, OleAndreasER commented on app/src/main/kotlin/com/platform/openemoji/screens/SearchScreen.kt
> +                maxEmojisPerGrid = 15,
Your solution works, so I will take care of this in another issue.

2024-03-08 08:36 UTC, OleAndreasER approved these changes

2024-03-08 08:36 UTC, merged