72 composable for webviewlink to events
ITP2-G15/OpenEmojiPlatform pull request #89
Opened 2024-03-21 14:22 UTC by Steffenriv

Composable for events is done, also finished eventListScreen to view all events and topics. Added tests, and navigation between screens and also navigation to event url. TODO: replace static data with mock data, will be done in another issue.
Closes #72

2024-03-22 10:34 UTC, OleAndreasER requested changes
This is good stuff.

2024-03-22 10:34 UTC, OleAndreasER commented on app/src/androidTest/kotlin/com/platform/platform/openemoji/navigation/NavigationTest.kt
> +        Thread.sleep(1000)
Don't sleep in tests. You should instead wait for a node to appear.

2024-03-22 10:34 UTC, OleAndreasER commented on app/src/main/kotlin/com/platform/openemoji/events/EventCard.kt
> +            data = event.img,
rememberImagePainter is deprecated. I don't know if this is an issue at all, so you can decide if it is.

2024-03-24 14:18 UTC, Steffenriv commented on app/src/main/kotlin/com/platform/openemoji/events/EventCard.kt
> +            data = event.img,
replaced with AsyncImage

2024-03-26 09:30 UTC, OleAndreasER commented on app/src/androidTest/kotlin/com/platform/platform/openemoji/navigation/NavigationTest.kt
>  }
Sorry for the late update. You forgot to remove the comment about sleep. Also, was the sleep not needed then?

2024-03-26 13:23 UTC, Steffenriv commented on app/src/androidTest/kotlin/com/platform/platform/openemoji/navigation/NavigationTest.kt
>  }
It's fine it is easter after all. Sleep was not needed indeed, will remove the comment now!

2024-03-26 14:39 UTC, merged